Minor typo fixes and requirement bump
realslimshanky/Just-Jobs-Bot pull request #6
Opened 2019-10-07 08:03 UTC by tanmaymohan

Fixed :

- Typos

- Requirements

2019-10-13 19:13 UTC, realslimshanky requested changes
Please remove unnecessary file.

2019-10-13 19:13 UTC, realslimshanky commented on requirements.txt
> -requests==2.18.4
Please remove this change from this PR as it's not relevant.

2019-10-14 07:21 UTC, tanmaymohan commented
Reverted

2020-02-21 11:24 UTC, realslimshanky approved these changes

2020-02-21 11:24 UTC, merged